/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

/**
 *
 * @author vitin
 */
public class Tela_Principal_Cadastro_Professor extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Principal_Cadastro_Professor
     */
    public Tela_Principal_Cadastro_Professor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastroProfessor = new javax.swing.JLabel();
        IdentidadeProfessor = new javax.swing.JLabel();
        TxtIdentProf = new javax.swing.JTextField();
        NomeProfessor = new javax.swing.JLabel();
        TxtNomeProf = new javax.swing.JTextField();
        DataNasci = new javax.swing.JLabel();
        TxtDataNasci = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox_Digito = new javax.swing.JCheckBox();
        jCheckBox_Informatica = new javax.swing.JCheckBox();
        jCheckBox_Matematica = new javax.swing.JCheckBox();
        jCheckBox_Medicina = new javax.swing.JCheckBox();
        TituloProfessor = new javax.swing.JLabel();
        jCheckBox_Bacharel = new javax.swing.JCheckBox();
        jCheckBox_Especialista = new javax.swing.JCheckBox();
        jCheckBox_Mestrado = new javax.swing.JCheckBox();
        jCheckBox_Doutorado = new javax.swing.JCheckBox();
        Endereco = new javax.swing.JLabel();
        TxtEnd = new javax.swing.JTextField();
        Numero = new javax.swing.JLabel();
        TxtNum = new javax.swing.JTextField();
        Bairro = new javax.swing.JLabel();
        TxtBairro = new javax.swing.JTextField();
        Cidade = new javax.swing.JLabel();
        TxtCidade = new javax.swing.JTextField();
        Estado = new javax.swing.JLabel();
        TxtEstado = new javax.swing.JTextField();
        TelFixo = new javax.swing.JLabel();
        TxtTelFixo = new javax.swing.JTextField();
        TelCel = new javax.swing.JLabel();
        TxtTelCel = new javax.swing.JTextField();
        Cadastrar_Professor = new javax.swing.JButton();
        Limpar_Professor = new javax.swing.JButton();
        Finalizar_Professor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        CadastroProfessor.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        CadastroProfessor.setText("CADASTRO DE PROFESSOR");

        IdentidadeProfessor.setText("Identidade Professor:");

        NomeProfessor.setText("Nome Professor:");

        DataNasci.setText("Data de Nasc:");

        jLabel1.setText("Especif Prof:");

        jCheckBox_Digito.setText("Digito");

        jCheckBox_Informatica.setText("Informatica");

        jCheckBox_Matematica.setText("Matematica");

        jCheckBox_Medicina.setText("Medicina");

        TituloProfessor.setText("Título Prof:");

        jCheckBox_Bacharel.setText("Bacharel");

        jCheckBox_Especialista.setText("Especialista");

        jCheckBox_Mestrado.setText("Mestrado");

        jCheckBox_Doutorado.setText("Doutorado");

        Endereco.setText("Endereço:");

        Numero.setText("Numero:");

        Bairro.setText("Bairro:");

        Cidade.setText("Cidade:");

        Estado.setText("Estado:");

        TelFixo.setText("Tel.Fixo");

        TelCel.setText("Tel.Cel");

        Cadastrar_Professor.setText("Cadastrar");

        Limpar_Professor.setText("Limpar");

        Finalizar_Professor.setText("Finalizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(CadastroProfessor))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IdentidadeProfessor)
                                    .addComponent(NomeProfessor)
                                    .addComponent(DataNasci)
                                    .addComponent(jCheckBox_Digito)
                                    .addComponent(jLabel1)
                                    .addComponent(jCheckBox_Informatica)
                                    .addComponent(jCheckBox_Medicina)
                                    .addComponent(jCheckBox_Matematica))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Cadastrar_Professor)
                                .addGap(38, 38, 38)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox_Bacharel)
                            .addComponent(jCheckBox_Especialista)
                            .addComponent(jCheckBox_Mestrado)
                            .addComponent(jCheckBox_Doutorado)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TxtNomeProf, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(TxtIdentProf)
                                        .addComponent(TxtDataNasci))
                                    .addComponent(TituloProfessor))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Endereco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Numero)
                                            .addComponent(Bairro)
                                            .addComponent(Cidade)
                                            .addComponent(Estado))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TxtTelCel)
                                            .addComponent(TxtTelFixo)
                                            .addComponent(TxtEstado)
                                            .addComponent(TxtNum)
                                            .addComponent(TxtBairro)
                                            .addComponent(TxtCidade)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TelCel)
                                                    .addComponent(TelFixo))
                                                .addGap(0, 130, Short.MAX_VALUE))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Limpar_Professor)
                                .addGap(48, 48, 48)
                                .addComponent(Finalizar_Professor)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CadastroProfessor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdentidadeProfessor)
                    .addComponent(TxtIdentProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Endereco)
                        .addComponent(TxtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeProfessor)
                    .addComponent(TxtNomeProf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero)
                    .addComponent(TxtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataNasci)
                    .addComponent(TxtDataNasci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bairro)
                    .addComponent(TxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TituloProfessor)
                    .addComponent(Cidade)
                    .addComponent(TxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Digito)
                    .addComponent(jCheckBox_Bacharel)
                    .addComponent(Estado)
                    .addComponent(TxtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Informatica)
                    .addComponent(jCheckBox_Especialista)
                    .addComponent(TelFixo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Matematica)
                    .addComponent(jCheckBox_Mestrado)
                    .addComponent(TxtTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Medicina)
                    .addComponent(jCheckBox_Doutorado)
                    .addComponent(TelCel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtTelCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastrar_Professor)
                    .addComponent(Limpar_Professor)
                    .addComponent(Finalizar_Professor))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal_Cadastro_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal_Cadastro_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal_Cadastro_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal_Cadastro_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal_Cadastro_Professor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bairro;
    private javax.swing.JButton Cadastrar_Professor;
    private javax.swing.JLabel CadastroProfessor;
    private javax.swing.JLabel Cidade;
    private javax.swing.JLabel DataNasci;
    private javax.swing.JLabel Endereco;
    private javax.swing.JLabel Estado;
    private javax.swing.JButton Finalizar_Professor;
    private javax.swing.JLabel IdentidadeProfessor;
    private javax.swing.JButton Limpar_Professor;
    private javax.swing.JLabel NomeProfessor;
    private javax.swing.JLabel Numero;
    private javax.swing.JLabel TelCel;
    private javax.swing.JLabel TelFixo;
    private javax.swing.JLabel TituloProfessor;
    private javax.swing.JTextField TxtBairro;
    private javax.swing.JTextField TxtCidade;
    private javax.swing.JTextField TxtDataNasci;
    private javax.swing.JTextField TxtEnd;
    private javax.swing.JTextField TxtEstado;
    private javax.swing.JTextField TxtIdentProf;
    private javax.swing.JTextField TxtNomeProf;
    private javax.swing.JTextField TxtNum;
    private javax.swing.JTextField TxtTelCel;
    private javax.swing.JTextField TxtTelFixo;
    private javax.swing.JCheckBox jCheckBox_Bacharel;
    private javax.swing.JCheckBox jCheckBox_Digito;
    private javax.swing.JCheckBox jCheckBox_Doutorado;
    private javax.swing.JCheckBox jCheckBox_Especialista;
    private javax.swing.JCheckBox jCheckBox_Informatica;
    private javax.swing.JCheckBox jCheckBox_Matematica;
    private javax.swing.JCheckBox jCheckBox_Medicina;
    private javax.swing.JCheckBox jCheckBox_Mestrado;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
