/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

/**
 *
 * @author vitin
 */
public class Tela_Principal_Manutencao_Professor extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Principal_Manutencao_Professor
     */
    public Tela_Principal_Manutencao_Professor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CadastroProfessor2 = new javax.swing.JLabel();
        IdentidadeProfessor2 = new javax.swing.JLabel();
        TxtIdentProf2 = new javax.swing.JTextField();
        NomeProfessor2 = new javax.swing.JLabel();
        TxtNomeProf2 = new javax.swing.JTextField();
        DataNasci2 = new javax.swing.JLabel();
        TxtDataNasci2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jCheckBox_Digito2 = new javax.swing.JCheckBox();
        jCheckBox_Informatica2 = new javax.swing.JCheckBox();
        jCheckBox_Matematica2 = new javax.swing.JCheckBox();
        jCheckBox_Medicina2 = new javax.swing.JCheckBox();
        TituloProfessor2 = new javax.swing.JLabel();
        jCheckBox_Bacharel2 = new javax.swing.JCheckBox();
        jCheckBox_Especialista2 = new javax.swing.JCheckBox();
        jCheckBox_Mestrado2 = new javax.swing.JCheckBox();
        jCheckBox_Doutorado2 = new javax.swing.JCheckBox();
        Endereco2 = new javax.swing.JLabel();
        TxtEnd2 = new javax.swing.JTextField();
        Numero2 = new javax.swing.JLabel();
        TxtNum2 = new javax.swing.JTextField();
        Bairro2 = new javax.swing.JLabel();
        TxtBairro2 = new javax.swing.JTextField();
        Cidade2 = new javax.swing.JLabel();
        TxtCidade2 = new javax.swing.JTextField();
        Estado2 = new javax.swing.JLabel();
        TxtEstado2 = new javax.swing.JTextField();
        TelFixo2 = new javax.swing.JLabel();
        TxtTelFixo2 = new javax.swing.JTextField();
        TelCel2 = new javax.swing.JLabel();
        TxtTelCel2 = new javax.swing.JTextField();
        Alterar_Professor = new javax.swing.JButton();
        Excluir_Professor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        CadastroProfessor2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        CadastroProfessor2.setText("PROFESSOR");

        IdentidadeProfessor2.setText("Identidade Professor:");

        NomeProfessor2.setText("Nome Professor:");

        DataNasci2.setText("Data de Nasc:");

        jLabel12.setText("Especif Prof:");

        jCheckBox_Digito2.setText("Digito");

        jCheckBox_Informatica2.setText("Informatica");

        jCheckBox_Matematica2.setText("Matematica");

        jCheckBox_Medicina2.setText("Medicina");

        TituloProfessor2.setText("Título Prof:");

        jCheckBox_Bacharel2.setText("Bacharel");

        jCheckBox_Especialista2.setText("Especialista");

        jCheckBox_Mestrado2.setText("Mestrado");

        jCheckBox_Doutorado2.setText("Doutorado");

        Endereco2.setText("Endereço:");

        Numero2.setText("Numero:");

        Bairro2.setText("Bairro:");

        Cidade2.setText("Cidade:");

        Estado2.setText("Estado:");

        TelFixo2.setText("Tel.Fixo");

        TelCel2.setText("Tel.Cel");

        Alterar_Professor.setText("Alterar");

        Excluir_Professor.setText("Excluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(CadastroProfessor2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IdentidadeProfessor2)
                                    .addComponent(NomeProfessor2)
                                    .addComponent(DataNasci2)
                                    .addComponent(jCheckBox_Digito2)
                                    .addComponent(jLabel12)
                                    .addComponent(jCheckBox_Informatica2)
                                    .addComponent(jCheckBox_Medicina2)
                                    .addComponent(jCheckBox_Matematica2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Alterar_Professor)
                                .addGap(38, 38, 38)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox_Bacharel2)
                            .addComponent(jCheckBox_Especialista2)
                            .addComponent(jCheckBox_Mestrado2)
                            .addComponent(jCheckBox_Doutorado2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TxtNomeProf2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(TxtIdentProf2)
                                        .addComponent(TxtDataNasci2))
                                    .addComponent(TituloProfessor2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Endereco2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TxtEnd2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Numero2)
                                            .addComponent(Bairro2)
                                            .addComponent(Cidade2)
                                            .addComponent(Estado2))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TxtTelCel2)
                                            .addComponent(TxtTelFixo2)
                                            .addComponent(TxtEstado2)
                                            .addComponent(TxtNum2)
                                            .addComponent(TxtBairro2)
                                            .addComponent(TxtCidade2)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(TelCel2)
                                                    .addComponent(TelFixo2))
                                                .addGap(0, 130, Short.MAX_VALUE))))))
                            .addComponent(Excluir_Professor))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CadastroProfessor2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IdentidadeProfessor2)
                    .addComponent(TxtIdentProf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Endereco2)
                        .addComponent(TxtEnd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NomeProfessor2)
                    .addComponent(TxtNomeProf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero2)
                    .addComponent(TxtNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataNasci2)
                    .addComponent(TxtDataNasci2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bairro2)
                    .addComponent(TxtBairro2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TituloProfessor2)
                    .addComponent(Cidade2)
                    .addComponent(TxtCidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Digito2)
                    .addComponent(jCheckBox_Bacharel2)
                    .addComponent(Estado2)
                    .addComponent(TxtEstado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Informatica2)
                    .addComponent(jCheckBox_Especialista2)
                    .addComponent(TelFixo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Matematica2)
                    .addComponent(jCheckBox_Mestrado2)
                    .addComponent(TxtTelFixo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox_Medicina2)
                    .addComponent(jCheckBox_Doutorado2)
                    .addComponent(TelCel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtTelCel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Alterar_Professor)
                    .addComponent(Excluir_Professor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal_Manutencao_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal_Manutencao_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal_Manutencao_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal_Manutencao_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal_Manutencao_Professor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Alterar_Professor;
    private javax.swing.JLabel Bairro2;
    private javax.swing.JLabel CadastroProfessor2;
    private javax.swing.JLabel Cidade2;
    private javax.swing.JLabel DataNasci2;
    private javax.swing.JLabel Endereco2;
    private javax.swing.JLabel Estado2;
    private javax.swing.JButton Excluir_Professor;
    private javax.swing.JLabel IdentidadeProfessor2;
    private javax.swing.JLabel NomeProfessor2;
    private javax.swing.JLabel Numero2;
    private javax.swing.JLabel TelCel2;
    private javax.swing.JLabel TelFixo2;
    private javax.swing.JLabel TituloProfessor2;
    private javax.swing.JTextField TxtBairro2;
    private javax.swing.JTextField TxtCidade2;
    private javax.swing.JTextField TxtDataNasci2;
    private javax.swing.JTextField TxtEnd2;
    private javax.swing.JTextField TxtEstado2;
    private javax.swing.JTextField TxtIdentProf2;
    private javax.swing.JTextField TxtNomeProf2;
    private javax.swing.JTextField TxtNum2;
    private javax.swing.JTextField TxtTelCel2;
    private javax.swing.JTextField TxtTelFixo2;
    private javax.swing.JCheckBox jCheckBox_Bacharel2;
    private javax.swing.JCheckBox jCheckBox_Digito2;
    private javax.swing.JCheckBox jCheckBox_Doutorado2;
    private javax.swing.JCheckBox jCheckBox_Especialista2;
    private javax.swing.JCheckBox jCheckBox_Informatica2;
    private javax.swing.JCheckBox jCheckBox_Matematica2;
    private javax.swing.JCheckBox jCheckBox_Medicina2;
    private javax.swing.JCheckBox jCheckBox_Mestrado2;
    private javax.swing.JLabel jLabel12;
    // End of variables declaration//GEN-END:variables
}
